### PR TITLE
Notify user via email.

### PR DESCRIPTION
**Pull request by kbohinski**

### CODE REVIEW

**Review by carlosesilva — CHANGES_REQUESTED** [review]
Hi Kevin, thanks so much for contributing!

I noticed that a lot of people that wanted to use this tool were not very tech savy and so I have some concerns about asking them to write their password into a plain text file since they probably don't know the security implications this may entail.

Maybe take a look at `gmail-sender-oauth` or some other package that doesn't require the user to provide their account's password?

Also, if you can, please update the readme file explaining the set up and how to use the email functionality so that those users with less coding experience don't have to read through the code to learn how to use it.

Again, thanks so much for contributing, I really appreciate it. I am just concerned about those less experienced users' safety.

**Comment by jboone0052** [comment]
Not sure where to put this since I'm relatively new to git, so if it would be better asked somewhere else, I'm open to guidance. But would you be open to a pull request that includes twilio and texting the user when it becomes available? Also I've updated it so that you can enter a zip code distance to look in as by default it found some 160 miles from my location so I only wanted to look at the apple stores near me.

**Comment by carlosesilva** [comment]
Hi @jboone0052! Yes, I am ok with twilio as long as the process is very well documented in the README so they know what twilio is, how to get an api key/token of their own and how to set it up with this project.

**Comment by rogerp25** [comment]
Hi @carlosesilva. I’m new to this whole coding thing. What would I have to do to run your genius coding so I can start check Apple Stores around me?
Thanks for creating this!

**Comment by kbohinski** [comment]
I'll look into `gmail-sender-oauth`. I should be able to get twilio integrated soon as well. 👍

**Comment by carlosesilva** [comment]
@rogerp25 please follow the instructions on the [README.md](https://github.com/carlosesilva/iphone-x-availability-node-cli/blob/master/README.md) and if you have no coding experience you can follow the instructions for non-coders that someone posted on this [reddit post](https://www.reddit.com/r/apple/comments/7bziwa/i_wrote_a_little_nodejs_tool_to_help_me_find_an/dpm6rlg/)

**Comment by carlosesilva** [comment]
@kbohinski that would be great! Thanks!

**Pull request closed without merging**
